idf_component_register(SRCS "src/PQCMicro.cpp"
                            "src/crypto/common/aes.c"
                            "src/crypto/common/fips202.c"
                            "src/crypto/common/nistseedexpander.c"
                            "src/crypto/common/randombytes.c"
                            "src/crypto/common/sha2.c"
                            "src/crypto/common/sp800-185.c"
                            "src/crypto/ml-kem-512/cbd.c"
                            "src/crypto/ml-kem-512/indcpa.c"
                            "src/crypto/ml-kem-512/kem.c"
                            "src/crypto/ml-kem-512/ntt.c"
                            "src/crypto/ml-kem-512/poly.c"
                            "src/crypto/ml-kem-512/polyvec.c"
                            "src/crypto/ml-kem-512/reduce.c"
                            "src/crypto/ml-kem-512/symmetric-shake.c"
                            "src/crypto/ml-kem-512/verify.c"
                            "src/crypto/ml-dsa-44/ntt.c"
                            "src/crypto/ml-dsa-44/packing.c"
                            "src/crypto/ml-dsa-44/poly.c"
                            "src/crypto/ml-dsa-44/polyvec.c"
                            "src/crypto/ml-dsa-44/reduce.c"
                            "src/crypto/ml-dsa-44/rounding.c"
                            "src/crypto/ml-dsa-44/sign.c"
                            "src/crypto/ml-dsa-44/symmetric-shake.c"
                    INCLUDE_DIRS "src"
                    REQUIRES esp_hw_support)
