[platformio]
default_envs = esp32dev, stm32g431cb

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = 
    -D ESP32
    -O3

[env:stm32g431cb]
platform = ststm32
board = nucleo_g431rb
framework = arduino
build_flags = 
    -D STM32G4xx
    -O3

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = 
    -O3
; Warning: Arduino Uno might not have enough RAM for ML-KEM/ML-DSA.
